version: '2'
volumes:
  mysql-volume:
    external: true

services:
 mysql:
  image: mysql:5.7.12
  container_name: mysql
  volumes:
   - mysql-volume:/var/lib/mysql
  ports:
   - "3306"
  environment:
   - MYSQL_ROOT_PASSWORD=root
   - MYSQL_DATABASE=db
   - MYSQL_USER=blog-user
   - MYSQL_PASSWORD=supersecret

 ghost:
  image: scheele/my-ghost:2.0
  container_name: ghost
  depends_on:
    - mysql
  ports:
    - "2368:2368"
  environment:
    - CLOUDINARY_URL=cloudinary://578666321948431:KvmIEtZELPkSCPMhuf-cJsUWa_8@dkt6e9jwp
    - NODE_ENV=production
